FROM ubuntu:latest

RUN apt-get -qq update && \
    apt-get -qq upgrade && \
    apt-get -y install git perl curl wget ant ant-contrib build-essential && \
    wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get -qq update && \
    apt-get -qq install msopenjdk-11 && \
    apt-get -qq purge apt-transport-https wget && \
    apt-get -qq autoremove --purge && \
    rm -rf /var/lib/apt/lists/* && \
    echo java -Xshare:dump && \
    java -Xshare:dump 

ENV TEST_JDK_HOME="/usr"
ENV USE_TESTENV_PROPERTIES=true
ENV JDK_VERSION=11
ENV BUILD_LIST=functional